apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: go-api-app
  namespace: argocd
spec:
  destination:
    namespace: default
    server: "https://kubernetes.default.svc"
  project: default
  syncPolicy:
    automated: {}
  source:
    repoURL: "${github_repo_url}"
    targetRevision: main
    path: "./helm-chart/"
    helm:
      valueFiles:
      - values.yaml