name: GitOps Pipeline

on:
  push:
    branches:
      - main
env:
  RUN_NUMBER: ${{ github.run_number }}
  AUTH_GITHUB_USERNAME: ${{ secrets.AUTH_GITHUB_USERNAME }}
  AUTH_GITHUB_TOKEN: ${{ secrets.AUTH_GITHUB_TOKEN }}
  GIT_EMAIL: "guzelkhuz@gmail.com"
  GIT_NAME: "guzel.khuziakhmetova"

jobs:
  deploy:
    name: Deploy app
    environment: production
    runs-on: ubuntu-latest
    if: success()
    steps:
      - name: Checkout Code from repository
        uses: actions/checkout@v2
      - run: |
          terraform init -backend-config "secret_key=$OBJECT_STORAGE_SECRET_KEY" -backend-config "access_key=$OBJECT_STORAGE_ACCESS_KEY"
          terraform apply -auto-approve -var "service_account_token=$SERVICE_ACCOUNT_TOKEN" -var "auth_github_username=$AUTH_GITHUB_USRNAME" -var "auth_github_token=$AUTH_GITHUB_TOKEN" -var "object_storage_secret_key=$OBJECT_STORAGE_SECRET_KEY" -var "object_storage_access_key=$OBJECT_STORAGE_ACCESS_KEY" -var "environment=${{vars.ENVIRONMENT}}"
        env:
          OBJECT_STORAGE_SECRET_KEY: ${{ secrets.OBJECT_STORAGE_SECRET_KEY }}
          OBJECT_STORAGE_ACCESS_KEY: ${{ secrets.OBJECT_STORAGE_ACCESS_KEY }}
          SERVICE_ACCOUNT_TOKEN: ${{ secrets.SERVICE_ACCOUNT_TOKEN }}
        name: Deploy app